message(STATUS "=== HPC Dialect Configuration ===")

# Backend Options
set(HPC_ENABLE_SIMD ON)
set(HPC_ENABLE_OPENMP ON)
set(HPC_ENABLE_MPI OFF)
set(HPC_ENABLE_CUDA OFF)

# BLAS/LAPACK Options
set(HPC_ENABLE_CUBLAS OFF)
set(HPC_ENABLE_OPENBLAS OFF)
set(HPC_ENABLE_ACCELERATE OFF)

# Compilation Options
set(HPC_USE_HIGH_LEVEL_OPTIMIZATIONS ON)
