# HPC Configuration for MLCC workspace
# This overrides HPC's default config when building as subdirectory

# Backend toggles
set(ENABLE_SIMD ON CACHE BOOL "" FORCE)
set(ENABLE_OPENMP ON CACHE BOOL "" FORCE)
set(ENABLE_MPI OFF CACHE BOOL "" FORCE)
set(ENABLE_CUDA OFF CACHE BOOL "" FORCE)

# BLAS/LAPACK
set(ENABLE_ACCELERATE OFF CACHE BOOL "" FORCE)

# Python
set(ENABLE_PYBIND11 OFF CACHE BOOL "" FORCE)
set(ENABLE_PYTORCH OFF CACHE BOOL "" FORCE)

# Optimizations
set(USE_HIGH_LEVEL_OPTIMIZATIONS ON CACHE BOOL "" FORCE)

# Don't build extras
set(ENABLE_BENCHMARKING OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
